# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions

# The other workflow does not work on pushes to the master branch because the git
# diff comparison with the master is identical to the branch on which the workflow
# is running. In this workflow we  grep git log for  pull requests, indicated
# in the log by the pull request number e.g. (#163) and then
# compare the current branch to the last two merges. For merged pull requests, this
# finds Rmds that are not the same as those in most recent merge. For pushes which
# Preceptor makes from the local master to origin, this compare, this finds Rmds that
# are not the same as in the last two merges. To avoid testing the same Rmd twice,
# sort -u is used.

on:
  push:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install gdal
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::renv
            any::rcmdcheck
        env:
          R_LIBS_USER: ~/Library/Application Support/renv
          GITHUB_ACTION: TRUE
      - name: Check
        run: |
          system('git log --grep="(#" --pretty=oneline -2 | sed "s/ .*//g" > last_merge')
          for(i in system('while read line; do git diff --name-only "$line" HEAD; done < last_merge | grep Rmd | sort -u', intern = TRUE)) {
          knitr::knit2html(i)
          }
        shell: Rscript {0}
